<a href="https://colab.research.google.com/github/oscarstivenmoreno2008-coder/Porgramacion/blob/main/parcial%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

oscar stiven moreno guerrero 2261347
parcial 2

Parte II

instruccion 1

In [79]:
import numpy as np
import pandas as pd

np.random.seed(0)
datos = np.random.randint(109, 197, 50)
datos

array([153, 156, 173, 176, 176, 118, 192, 130, 145, 196, 179, 121, 167,
       174, 148, 196, 155, 190, 146, 134, 186, 181, 118, 129, 189, 178,
       188, 156, 173, 191, 158, 138, 128, 128, 123, 148, 141, 174, 118,
       166, 141, 140, 183, 132, 144, 184, 164, 137, 143, 109])

In [80]:
np.unique(datos)

array([109, 118, 121, 123, 128, 129, 130, 132, 134, 137, 138, 140, 141,
       143, 144, 145, 146, 148, 153, 155, 156, 158, 164, 166, 167, 173,
       174, 176, 178, 179, 181, 183, 184, 186, 188, 189, 190, 191, 192,
       196])

In [81]:
media = np.mean(datos)
media

np.float64(156.26)

In [82]:
desviación = np.std(datos)
desviación

np.float64(24.618537730742663)

In [95]:
lambda x: (x - x.mean(156.26)) / x.std(24.618537730742663)

In [96]:
df.describe()

            datos
count   50.000000
mean   156.260000
std     24.868479
min    109.000000
25%    137.250000
50%    155.500000
75%    177.500000
max    196.000000

In [97]:
df = pd.DataFrame({
    "datos": datos
})
df

    datos
0     153
1     156
2     173
3     176
4     176
5     118
6     192
7     130
8     145
9     196
10    179
11    121
12    167
13    174
14    148
15    196
16    155
17    190
18    146
19    134
20    186
21    181
22    118
23    129
24    189
25    178
26    188
27    156
28    173
29    191
30    158
31    138
32    128
33    128
34    123
35    148
36    141
37    174
38    118
39    166
40    141
41    140
42    183
43    132
44    144
45    184
46    164
47    137
48    143
49    109

In [ ]:
instruccion 2

In [38]:
import pandas as pd
datos2 = pd.DataFrame({
    "nombre":["juan", "Luis", "Carlos", "valentina", "oscar"],
    "edad": [23, 30, 25, 26, 17],
    "nota": [4.5, 3.8, 4.2, 2.5, 5.0],
    "ciudad": ["bogota", "medellin", "cali", "barranquilla", "bucaramanga"]
})
datos2

      nombre  edad  nota        ciudad
0       juan    23   4.5        bogota
1       Luis    30   3.8      medellin
2     Carlos    25   4.2          cali
3  valentina    26   2.5  barranquilla
4      oscar    17   5.0   bucaramanga

In [43]:
datos2.head(0)
datos2.head(1)
datos2.head(2)

  nombre  edad  nota    ciudad
0   juan    23   4.5    bogota
1   Luis    30   3.8  medellin

In [68]:
datos2['edad']

0    23
1    30
2    25
3    26
4    17
Name: edad, dtype: int64

In [107]:
datos2['nota']

0    4.5
1    3.8
2    4.2
3    2.5
4    5.0
Name: nota, dtype: float64

In [54]:
datos2.iloc[0]

nombre      juan
edad          23
nota         4.5
ciudad    bogota
Name: 0, dtype: object

parte III

In [115]:
import numpy as np
import pandas as pd
np.random.seed(59)

In [ ]:
from sc

In [117]:
prueba 2 = np.random.gamma(shape=306, scale=0.0229, size=59)

SyntaxError: invalid syntax (2448063000.py, line 1)

In [ ]:
# CREAR UN CSV:
from google.colab import files
import csv
datos = [
    ["Nombre", "Edad", "Ciudad"],
    ["Ana", 25, "Bogotá"],
    ["Luis", 30, "Medellín"],
    ["Carlos", 28, "Cali"]
]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

files.download("datos.csv")